"""
evaluate.py
===========
Compute quality metrics on predictions generated by inference.py.

Metrics reported:
  - ROUGE-1 / ROUGE-2 / ROUGE-L  (overall and per waveform type)
  - Section-level ROUGE-L         (DEVIATION SUMMARY and CORRECTION VECTOR separately)
  - Inference speed               (avg / min / max ms per sample)

Run locally after downloading results/predictions_test.jsonl from the cluster:
    pip install rouge-score
    python evaluate.py --predictions ./results/predictions_test.jsonl
"""

import argparse
import json
from collections import defaultdict

from rouge_score import rouge_scorer


def load_jsonl(path: str) -> list[dict]:
    with open(path) as f:
        return [json.loads(line) for line in f if line.strip()]


def extract_section(text: str, header: str) -> str:
    idx = text.find(header)
    if idx == -1:
        return ""
    start = idx + len(header)
    all_headers = [
        "DEVIATION SUMMARY:", "TEMPORAL DEVIATION:",
        "VIBRATION ANALYSIS:", "CORRECTION VECTOR:",
    ]
    end = len(text)
    for h in all_headers:
        if h == header:
            continue
        j = text.find(h, start)
        if j != -1 and j < end:
            end = j
    return text[start:end].strip()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--predictions", default="./results/predictions_test.jsonl")
    args = parser.parse_args()

    data = load_jsonl(args.predictions)
    print(f"Loaded {len(data)} predictions from {args.predictions}\n")

    scorer  = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=False)
    metrics = ["rouge1", "rouge2", "rougeL"]

    totals  = defaultdict(lambda: defaultdict(float))
    by_wave = defaultdict(lambda: defaultdict(lambda: defaultdict(float)))
    counts  = defaultdict(int)

    section_keys   = ["DEVIATION SUMMARY:", "CORRECTION VECTOR:"]
    section_totals = {s: defaultdict(float) for s in section_keys}
    section_counts = {s: 0 for s in section_keys}

    speed_ms = []

    for item in data:
        ref = item["reference"]
        gen = item["generated"]
        wv  = item.get("waveform", "unknown")
        counts[wv] += 1

        if "ms" in item:
            speed_ms.append(item["ms"])

        scores = scorer.score(ref, gen)
        for m in metrics:
            totals[m]["precision"] += scores[m].precision
            totals[m]["recall"]    += scores[m].recall
            totals[m]["fmeasure"]  += scores[m].fmeasure
            by_wave[wv][m]["fmeasure"] += scores[m].fmeasure

        for sec in section_keys:
            r = extract_section(ref, sec)
            g = extract_section(gen, sec)
            if r and g:
                s = scorer.score(r, g)
                section_totals[sec]["rougeL"] += s["rougeL"].fmeasure
                section_counts[sec] += 1

    n = len(data)

    print("=" * 60)
    print(f"{'OVERALL ROUGE':^60}   (n={n})")
    print("=" * 60)
    print(f"{'Metric':<12}  {'Precision':>10}  {'Recall':>10}  {'F1':>10}")
    print("-" * 60)
    for m in metrics:
        p = totals[m]["precision"] / n
        r = totals[m]["recall"]    / n
        f = totals[m]["fmeasure"]  / n
        print(f"{m:<12}  {p:>10.4f}  {r:>10.4f}  {f:>10.4f}")

    print("\n" + "=" * 60)
    print(f"{'ROUGE-L F1 BY WAVEFORM':^60}")
    print("=" * 60)
    print(f"{'Waveform':<12}  {'n':>5}  {'ROUGE-1':>10}  {'ROUGE-2':>10}  {'ROUGE-L':>10}")
    print("-" * 60)
    for wv in sorted(counts):
        c  = counts[wv]
        r1 = by_wave[wv]["rouge1"]["fmeasure"] / c
        r2 = by_wave[wv]["rouge2"]["fmeasure"] / c
        rL = by_wave[wv]["rougeL"]["fmeasure"] / c
        print(f"{wv:<12}  {c:>5}  {r1:>10.4f}  {r2:>10.4f}  {rL:>10.4f}")

    print("\n" + "=" * 60)
    print(f"{'SECTION-LEVEL ROUGE-L F1':^60}")
    print("=" * 60)
    for sec in section_keys:
        c = section_counts[sec]
        if c > 0:
            f = section_totals[sec]["rougeL"] / c
            print(f"  {sec.replace(':', ''):<25}  {f:.4f}  (n={c})")

    if speed_ms:
        avg = sum(speed_ms) / len(speed_ms)
        print("\n" + "=" * 60)
        print(f"{'INFERENCE SPEED':^60}")
        print("=" * 60)
        print(f"  Avg : {avg:>8.1f} ms/sample")
        print(f"  Min : {min(speed_ms):>8.1f} ms/sample")
        print(f"  Max : {max(speed_ms):>8.1f} ms/sample")

    print()


if __name__ == "__main__":
    main()
